# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &mysql
  adapter: mysql2
  pool: 5
  timeout: 5000
  user : root
  password: 

development:
  <<: *mysql
  database: maybe_development

production:
  <<: *mysql
  database: maybe_production

test:
  <<: *mysql
  database: maybe_test
